// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mediaapi} from '../models';

export function GetAllThumbnails():Promise<Array<mediaapi.ThumbnailData>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetThumbnailBase64(arg1:string):Promise<string>;

export function ImportImage(arg1:string,arg2:Array<number>):Promise<string>;
