// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageBase64(arg1) {
  return window['go']['mediaapi']['MediaAPI']['GetImageBase64'](arg1);
}

export function GetThumbnailBase64(arg1) {
  return window['go']['mediaapi']['MediaAPI']['GetThumbnailBase64'](arg1);
}

export function ImportImage(arg1, arg2) {
  return window['go']['mediaapi']['MediaAPI']['ImportImage'](arg1, arg2);
}
