// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImageToAlbum(arg1, arg2) {
  return window['go']['mediaapi']['MediaAPI']['AddImageToAlbum'](arg1, arg2);
}

export function CreateAlbumIfMissing(arg1) {
  return window['go']['mediaapi']['MediaAPI']['CreateAlbumIfMissing'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['mediaapi']['MediaAPI']['CreateTag'](arg1);
}

export function GetAllThumbnails() {
  return window['go']['mediaapi']['MediaAPI']['GetAllThumbnails']();
}

export function GetImageBase64(arg1) {
  return window['go']['mediaapi']['MediaAPI']['GetImageBase64'](arg1);
}

export function GetImagesWithTag(arg1) {
  return window['go']['mediaapi']['MediaAPI']['GetImagesWithTag'](arg1);
}

export function GetTagsForImage(arg1) {
  return window['go']['mediaapi']['MediaAPI']['GetTagsForImage'](arg1);
}

export function GetThumbnailBase64(arg1) {
  return window['go']['mediaapi']['MediaAPI']['GetThumbnailBase64'](arg1);
}

export function ImportImage(arg1, arg2) {
  return window['go']['mediaapi']['MediaAPI']['ImportImage'](arg1, arg2);
}

export function ImportImagesFromDirectory(arg1) {
  return window['go']['mediaapi']['MediaAPI']['ImportImagesFromDirectory'](arg1);
}

export function ListAlbumIDsForImage(arg1) {
  return window['go']['mediaapi']['MediaAPI']['ListAlbumIDsForImage'](arg1);
}

export function ListAlbumNamesForImage(arg1) {
  return window['go']['mediaapi']['MediaAPI']['ListAlbumNamesForImage'](arg1);
}

export function ListAllAlbums() {
  return window['go']['mediaapi']['MediaAPI']['ListAllAlbums']();
}

export function ListAllTags() {
  return window['go']['mediaapi']['MediaAPI']['ListAllTags']();
}

export function ListImagesInAlbum(arg1) {
  return window['go']['mediaapi']['MediaAPI']['ListImagesInAlbum'](arg1);
}

export function ResolveOrCreateMimeType(arg1) {
  return window['go']['mediaapi']['MediaAPI']['ResolveOrCreateMimeType'](arg1);
}

export function TagImage(arg1, arg2) {
  return window['go']['mediaapi']['MediaAPI']['TagImage'](arg1, arg2);
}
