// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mediaapi} from '../models';
import {metadata} from '../models';

export function AddImageToAlbum(arg1:string,arg2:string):Promise<void>;

export function CreateAlbumIfMissing(arg1:string):Promise<string>;

export function CreateTag(arg1:string):Promise<string>;

export function GetAllThumbnails():Promise<Array<mediaapi.ThumbnailData>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImagesWithTag(arg1:string):Promise<Array<string>>;

export function GetTagsForImage(arg1:string):Promise<Array<string>>;

export function GetThumbnailBase64(arg1:string):Promise<string>;

export function ImportImage(arg1:string,arg2:Array<number>):Promise<string>;

export function ImportImagesFromDirectory(arg1:string):Promise<void>;

export function ListAlbumIDsForImage(arg1:string):Promise<Array<string>>;

export function ListAlbumNamesForImage(arg1:string):Promise<Array<string>>;

export function ListAllAlbums():Promise<Array<metadata.SelectAllAlbumsWithImageCountRow>>;

export function ListAllTags():Promise<Array<string>>;

export function ListImagesInAlbum(arg1:string):Promise<Array<metadata.Image>>;

export function ResolveOrCreateMimeType(arg1:string):Promise<number>;

export function TagImage(arg1:string,arg2:string):Promise<void>;
