// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTags(arg1) {
  return window['go']['bridge']['Bridge']['GetTags'](arg1);
}
